from enum import Enum

class GameStates(Enum):
	PLAYERS_TURN = 1
	ENEMY_TURN = 2
	PLAYER_DEAD = 3
	SHOW_INVENTORY = 4
	DROP_INVENTORY = 5
	TARGETING = 6
	LEVEL_UP = 7
	CHARACTER_SCREEN = 8
	CONTROLS_SCREEN = 9
	INTERACT = 10
	SELECT_RACE = 11
	SELECT_CLASS = 12
	ENTER_PLAYER_NAME = 13
	CHOOSE_ITEM_TO_INSPECT = 14
	INSPECT_ITEM = 15
	SELECT_SEX = 16